<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Products">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Product" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id"          type="xs:positiveInteger" />
              <xs:element name="Name"        type="nonEmptyString" />
              <xs:element name="Description" type="xs:string" />
              <xs:element name="Price"       type="positiveDecimal" />
              <xs:element name="Category"    type="xs:string" />
              <xs:element name="Brand"       type="xs:string" />
              <xs:element name="Rating"      type="xs:decimal" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="positiveDecimal">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="nonEmptyString">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>
